var translations = {
  tr: {

      'titlelogin': 'GİRİŞ YAP',
      'login': 'GİRİŞ YAP',
      'register': 'Kayıt Ol',
      'intra' : '42 İntra ile Giriş Yap',
      'welcome': '42 Transcendence Projesine Hoşgeldin',
      'aimode': 'Yapay Zeka İle Oyna',
      'Tournament' : 'Turnuva',
      'ponggame' : '🏓 Pong Oyunu 🏓',
      'turnuvaolustur' : '🏆Turnuva Oluştur🏆',
      'turnuvaolusturbuton' : 'Turnuva Oluştur',
      'turnuvaadı' : 'Turnuva Adı',
      'oyuncuekle' : 'Oyuncu Ekle',
      'tournamentt': 'Turnuva Modu',
      'turnuva': '👤 Katılımcılar 👤',
      'TurnuvaStart': 'Turnuvayı Başlat',
      'welcomepong': 'Pong Oyununa Hoşgeldin',
      "choosetheme": "Aşağıdan bir tema seç!",
      "choosePerson": "Kişi seç!",
      'gameheader': 'Oyun',
      'chatheader': 'Sohbet',
      'profileheader': 'Profil',
      'settings': 'Ayarlar',
      'profileuser': 'Kullanıcı Adı',
      'profilefirstname': 'İsim',
      'profilenickname': 'Takma İsim',
      'profileemail': 'E-posta',
      'profilelastname': 'Soyad',
      'kullaniciayarlari':'Kullanıcı Ayarları',
      '' : 'Profil Fotoğrafı',
      'accountusername' : 'Kullanıcı Adı',
      'accountmail' : 'Email',
      'accountnickname' : 'Takma İsim',
      'accountfirstname' : 'İlk İsim',
      'accountlastname' : 'Soyad',
      'registertoproject' : 'Transcendence Projesine Kayıt Ol',
      'usrname' : 'Kullanıcı Adı',
      'registerbuton' : 'Kayıt Ol',
      'giristrans' : 'Transcendence Projesine Giriş Yap',
      'girisuser' : 'Kullanıcı Adı',
      'girispass' : 'Şifre',
      'girisbuttons' : 'Giriş Yap',
      'message' : 'mesaj',
      'block' : 'engelle',
      'invite' : 'davet et',
      'send' : 'Gönder',
      'save' : 'Kaydet',
      'profileusername' : 'Kullanıcı Adı',
      'profileemail' : 'E-mail',
      'profilefirstname' : 'İlk İsim',
      'profilelastname' : 'Soyadı',
      'back' : 'Geri',
      'chatmesajgonder' : 'Gönder',
      'chattemizle' : 'Temizle',
      'onlineusers' : 'Aktif Kullanıcı',
      'offlineusers' : 'Pasif Kullanıcı',
      'chatsettings' : 'Ayarlar',
      'addplayers' : 'Oyuncu Ekle',
      'addgameuser' : '🎮 Oyuna Davet Et ',
      'blockuser' : '❌ Engelle',
      'addfriend' : '➕ Arkadaş Ekle',
      'friends' : 'Arkadaşlar',
      'signupError' : 'Kullanıcı oluşturulamadı! Farklı bir kullanıcı adıyla tekrar dene!',
      'matchHistory' : 'Karşılaşma Geçmişi'
  },
  en: {
    'titlelogin': 'LOGIN',
    'login': 'LOGIN',
    'register': 'Register',
    'intra': 'Login with 42 Intra',
    'welcome': 'Welcome to the 42 Transcendence Project',
    'aimode': 'Play with AI',
    'Tournament': 'Tournament',
    'ponggame': '🏓 Pong Game 🏓',
    'turnuvaolustur': '🏆 Create Tournament 🏆',
    'turnuvaolusturbuton': 'Create Tournament',
    'turnuvaadı': 'Tournament Name',
    'oyuncuekle': 'Add Player',
    'tournamentt': 'Tournament Mode',
    'turnuva': '👤 Participants 👤',
    'TurnuvaStart': 'Start Tournament',
    'welcomepong': 'Welcome to Pong Game',
    'choosetheme': 'Choose a theme from below!',
    "choosePerson": "Choose person!",
    'gameheader': 'Game',
    'chatheader': 'Chat',
    'profileheader': 'Profile',
    'settings': 'Settings',
    'profileuser': 'Username',
    'profilefirstname': 'First Name',
    'profilenickname': 'Nickname',
    'profileemail': 'E-mail',
    'profilelastname': 'Last Name',
    'kullaniciayarlari': 'User Settings',
    '': 'Profile Picture',
    'accountusername': 'Username',
    'accountmail': 'Email',
    'accountnickname': 'Nickname',
    'accountfirstname': 'First Name',
    'accountlastname': 'Last Name',
    'registertoproject': 'Register to Transcendence Project',
    'usrname': 'Username',
    'registerbuton': 'Register',
    'giristrans': 'Login to Transcendence Project',
    'girisuser': 'Username',
    'girispass': 'Password',
    'girisbuttons': 'Login',
    'message': 'message',
    'block': 'block',
    'invite': 'invite',
    'send': 'Send',
    'save': 'Save',
    'profileusername': 'Username',
    'profileemail': 'E-mail',
    'profilefirstname': 'First Name',
    'profilelastname': 'Last Name',
    'back': 'Back',
    'chatmesajgonder': 'Send',
    'chattemizle': 'Clear',
    'onlineusers': 'Active Users',
    'offlineusers': 'Offline Users',
    'chatsettings': 'Settings',
    'addplayers': 'Add Players',
    'addgameuser': '🎮 Invite to Game',
    'blockuser': '❌ Block User',
    'addfriend': '➕ Add Friend',
    'friends' : 'Friends',
    'signupError' : 'Failed to create user! Try again with a different username!',
    'matchHistory' : 'Match History'
  },
  ru: {

    'titlelogin': 'ВХОД',
    'login': 'ВХОД',
    'register': 'Регистрация',
    'intra': 'Войти с 42 Интра',
    'welcome': 'Добро пожаловать в Проект 42 Transcendence',
    'aimode': 'Играть с ИИ',
    'Tournament': 'Турнир',
    'ponggame': '🏓 Игра в пинг-понг 🏓',
    'turnuvaolustur': '🏆 Создать турнир 🏆',
    'turnuvaolusturbuton': 'Создать турнир',
    'turnuvaadı': 'Название турнира',
    'oyuncuekle': 'Добавить игрока',
    'tournamentt': 'Режим турнира',
    'turnuva': '👤 Участники 👤',
    'TurnuvaStart': 'Начать турнир',
    'welcomepong': 'Добро пожаловать в игру в пинг-понг',
    'choosetheme': 'Выберите тему из списка ниже!',
    "choosePerson": "Киши Сеч!",
    'gameheader': 'Игра',
    'chatheader': 'Чат',
    'profileheader': 'Профиль',
    'settings': 'Настройки',
    'profileuser': 'Имя пользователя',
    'profilefirstname': 'Имя',
    'profilenickname': 'Псевдоним',
    'profileemail': 'Электронная почта',
    'profilelastname': 'Фамилия',
    'kullaniciayarlari': 'Настройки пользователя',
    '': 'Фото профиля',
    'accountusername': 'Имя пользователя',
    'accountmail': 'Электронная почта',
    'accountnickname': 'Псевдоним',
    'accountfirstname': 'Имя',
    'accountlastname': 'Фамилия',
    'registertoproject': 'Регистрация в Проекте Transcendence',
    'usrname': 'Имя пользователя',
    'registerbuton': 'Зарегистрироваться',
    'giristrans': 'Войти в Проект Transcendence',
    'girisuser': 'Имя пользователя',
    'girispass': 'Пароль',
    'girisbuttons': 'Вход',
    'message': 'сообщение',
    'block': 'блок',
    'invite': 'приглашение',
    'send': 'Отправить',
    'save': 'Сохранить',
    'profileusername': 'Имя пользователя',
    'profileemail': 'Электронная почта',
    'profilefirstname': 'Имя',
    'profilelastname': 'Фамилия',
    'back': 'Назад',
    'chatmesajgonder': 'Отправить',
    'chattemizle': 'Очистить',
    'onlineusers': 'Онлайн',
    'offlineusers': 'Оффлайн',
    'chatsettings': 'Настройки чата',
    'addplayers': 'Добавить игроков',
    'addgameuser': '🎮 Пригласить в игру',
    'blockuser': '❌ Заблокировать пользователя',
    'addfriend': '➕ Добавить друга',
    'friends' : 'Друзья',
    'signupError' : 'Не удалось создать пользователя! Попробуйте еще раз с другим именем пользователя!',
    'matchHistory' : 'История матчей'
  
  }
};

function changeLanguage(language) {
  document.querySelectorAll('[data-translate]').forEach(function(element) {
      var key = element.getAttribute('data-translate');
      element.textContent = translations[language][key];
  });
}

function language(language) {
  localStorage.setItem('selectedLanguage', language);
  changeLanguage(language);
}
