# Generated by Django 3.2.6 on 2024-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabloT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deger', models.CharField(max_length=255)),
            ],
        ),
    ]
