# Generated by Django 4.2.3 on 2024-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=60)),
                ('name', models.CharField(default='none', max_length=60)),
                ('surname', models.CharField(default='none', max_length=60)),
                ('email', models.CharField(default='none', max_length=60)),
                ('password', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
