# Generated by Django 3.2.12 on 2024-03-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('online', models.BooleanField(default=False)),
                ('securitykey', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('name', models.CharField(default='none', max_length=60)),
                ('surname', models.CharField(default='none', max_length=60)),
                ('email', models.CharField(default='none', max_length=60)),
                ('password', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
