# Generated by Django 4.2.3 on 2024-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
