# Generated by Django 3.2.12 on 2024-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='test',
            field=models.CharField(default='nn', max_length=100),
        ),
    ]
