# Generated by Django 3.2.12 on 2024-03-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_users_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='test',
        ),
    ]
