# Generated by Django 3.2.12 on 2024-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_users_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.CharField(default='notimg', max_length=1000),
        ),
    ]
