# Generated by Django 3.2.12 on 2024-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=100)),
                ('target_username', models.CharField(default='none', max_length=100)),
                ('room_id', models.CharField(default='none', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='login_42',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
