# Generated by Django 3.2.12 on 2024-04-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20240416_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=60)),
                ('friends', models.CharField(default='none', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
