# Generated by Django 3.2.12 on 2024-04-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20240422_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='backlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=60)),
                ('backfriends', models.CharField(default='none', max_length=60)),
            ],
        ),
    ]
