# Generated by Django 3.2.12 on 2024-04-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_backlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='backlist',
            new_name='darklist',
        ),
    ]
