# Generated by Django 3.2.12 on 2024-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_backfriends_darklist_darkfriends'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=60)),
                ('receiver_username', models.CharField(default='none', max_length=60)),
                ('score1', models.CharField(default='none', max_length=60)),
                ('score2', models.CharField(default='none', max_length=60)),
                ('date', models.CharField(default='none', max_length=60)),
            ],
        ),
    ]
