# Generated by Django 3.2.12 on 2024-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=60)),
                ('target_user_and_users', models.CharField(default='none', max_length=60)),
                ('massage', models.CharField(default='none', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
