# Generated by Django 3.2.12 on 2024-04-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20240323_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_message',
            old_name='target_user_and_users',
            new_name='room_id',
        ),
    ]
